#!/bin/sh

if [ "$1" = menu ]; then
	init-menu-add-entry "$0" "NAND partitions"
	exit
fi

mtdparts="1M(nand0.barebox)ro,1M(nand0.bareboxenv),4M(nand0.recovery),5M(nand0.kernel),3M(nand0.ramdisk),-(nand0.system)"
kernelname="s3c_nand"

mtdparts-add -b -d nand0 -k ${kernelname} -p ${mtdparts}
